"""adjusted user model to allow users to upload images for their banner

Revision ID: f539937bd3b5
Revises: 781381c97178
Create Date: 2023-07-26 17:29:47.334957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f539937bd3b5'
down_revision = '781381c97178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner_image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner_image3', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner_image3')
        batch_op.drop_column('banner_image2')
        batch_op.drop_column('banner_image1')

    # ### end Alembic commands ###
