"""model changes to add distance per activity

Revision ID: 781381c97178
Revises: 5bd35a8a72aa
Create Date: 2023-07-25 21:26:29.865263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781381c97178'
down_revision = '5bd35a8a72aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_distance_running', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_distance_cycling', sa.Float(), nullable=True))
        batch_op.drop_column('total_distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_distance', sa.FLOAT(), nullable=True))
        batch_op.drop_column('total_distance_cycling')
        batch_op.drop_column('total_distance_running')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###
